# Generated by Django 4.2.5 on 2023-09-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='materials_provided',
        ),
    ]
