# Generated by Django 4.2.5 on 2023-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_remove_form_materials_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='materials_provided',
            field=models.ManyToManyField(to='bankapp.materialoption'),
        ),
    ]
